#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,  but for the 9th iteration, displays Best School and then Hi on a new line.

z=0
while [ $z -lt 10 ]
do
	echo "Best School"
	if [ $z -eq 8 ]
	then
		echo "Hi"
	fi
	z=$(( z + 1 ))
done
