#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#	displays bad luck for the 4th loop iteration
#	displays good luck for the 8th loop iteration
#	displays Best School for the other iterations

z=0
while [ $z -lt 10 ]
do
	if [ $z -eq 3 ]
	then
		echo "bad luck"
	elif [ $z -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	z=$(( z + 1 ))
done
