#!/usr/bin/env bash
#print 1 hours after every 60 minutes

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour";
    minute=1;
    while [ $minute -lt 60 ]
    do
        echo "$minute";
        minute=$((minute + 1));
    done
    hour=$((hour + 1))
done
